name: doctor_house
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.1

  # Fonts
  google_fonts: ^6.2.1

  # FireBase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1

  # Page Indicator
  smooth_page_indicator: ^1.2.0+3

  # Liquid Swipe
  liquid_swipe: ^3.1.0

  # Go Router
  go_router: ^14.6.2

  # Data Store
  shared_preferences: ^2.3.3

  # Bloc
  flutter_bloc: ^8.1.6

  # Animation
  animate_do: ^3.3.4

  # Icons
  font_awesome_flutter: ^10.8.0

  # Keyboard
  flutter_keyboard_visibility: ^6.0.0

  # Google Sign in
  google_sign_in: ^6.2.2

  # Toast
  toastification: ^2.3.0

  # Svg
  flutter_svg: ^2.0.16

  # Image Picker
  image_picker: ^1.1.2

  # Country Code Picker
  country_code_picker: ^3.1.0







dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/svg/


  fonts:
    - family: SourceSerif4
      fonts:
        - asset: assets/fonts/SourceSerif4-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceSerif4-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceSerif4-Medium.ttf
          weight: 500
        - asset: assets/fonts/SourceSerif4-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSerif4-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceSerif4-Black.ttf
          weight: 800