import 'package:dr_house/utils/const/images.dart';

class Nlist {
  static const List docTypeIcon = [
    Nimages.generalPhy,
    Nimages.neurologist,
    Nimages.gynecologist,
    Nimages.cardiologist,
    Nimages.orthopedics,
    Nimages.dentist,
    Nimages.physician,
    Nimages.urologist,
    Nimages.oncologist,
    Nimages.dermatologist,
    Nimages.psychiatrist,
    Nimages.allergist,
    Nimages.otolaryngologists,
    Nimages.nephrologists,
  ];

  static const List docTypeName = [
    'General physician',
    'Neurologist',
    'Gynecologist',
    'Cardiologist',
    'Orthopedic',
    'Dentist',
    'Physician',
    'Urologist',
    'Oncologist',
    'Dermatologist',
    'Psychiatrist',
    'Allergist',
    'Otolaryngologists',
    'Nephrologists',
  ];
  static const List servicesIcon = [
    Nimages.appointment,
    Nimages.consultation,
    Nimages.medicalrecords,
    Nimages.healthtips,
  ];

  static const List servicesName = [
    'Appointment',
    'Consultation',
    'Medical Records',
    'Health Tips',
  ];

  static const List doctorCategories = [
    ' All ',
    'General physician',
    'Neurologist',
    'Gynecologist',
    'Cardiologist',
    'Orthopedic',
    'Dentist',
    'Physician',
    'Urologist',
    'Oncologist',
    'Dermatologist',
    'Psychiatrist',
    'Allergist',
    'Otolaryngologists',
    'Nephrologists',
  ];

  static List doclist = [
    {
      "id": 1,
      "name": "Dr. Arpita Joshi",
      "type": "Neurologist",
      "degree": "MBBS",
      "city": "Ahmedabad",
      "ratting": 4.1,
    },
    {
      "id": 2,
      "name": "Dr. Acharya Ishan",
      "type": "Dentist",
      "degree": "MBBS",
      "city": "Surat",
      "ratting": 4.5,
    },
    {
      "id": 3,
      "name": "Dr. Nivedita Kakkad",
      "type": "Dermatologist",
      "degree": "MBBS",
      "city": "Gandhinagar",
      "ratting": 4.5,
    },
    {
      "id": 4,
      "name": "Dr. Rupa Shah",
      "type": "General physician",
      "degree": "MBBS",
      "city": "Vadodara",
      "ratting": 4.3,
    },
    {
      "id": 5,
      "name": "Dr. Shivang Patel",
      "type": "Gynecologist",
      "degree": "MBBS",
      "city": "Amreli",
      "ratting": 4.8,
    },
    {
      "id": 6,
      "name": "Dr. Anshul Warman",
      "type": "Cardiologist",
      "degree": "MBBS",
      "city": "Vadodara",
      "ratting": 4.6,
    },
    {
      "id": 6,
      "name": "Dr. Purva Bambhania",
      "type": "Dermatologist",
      "degree": "MBBS",
      "city": "Ahmedabad",
      "ratting": 4.3,
    },
    {
      "id": 7,
      "name": "Dr. Meeta Desai",
      "type": "Orthopedic",
      "degree": "MBBS",
      "city": "Surat",
      "ratting": 4.0,
    },
    {
      "id": 8,
      "name": "Dr. Hiren Patel",
      "type": "Dermatologist",
      "degree": "MBBS",
      "city": "Surat",
      "ratting": 4.5,
    },
    {
      "id": 9,
      "name": "Dr. Neha Joshi",
      "type": "Dentist",
      "degree": "MBBS",
      "city": "Gandhinagar",
      "ratting": 4.7,
    },
    {
      "id": 10,
      "name": "Dr. Rashmi Shankar",
      "type": "Urologist",
      "degree": "MBBS",
      "city": "Vadodara",
      "ratting": 4.5,
    },
    {
      "id": 11,
      "name": "Dr. Pooja Chowdhary",
      "type": "Dermatologist",
      "degree": "MBBS",
      "city": "Amreli",
      "ratting": 4.9,
    },
  ];
}
